export const UPLOAD_AVATAR_INTO_S3_QUEUE = "UPLOAD_AVATAR_INTO_S3_QUEUE";
export const UPLOAD_AVATAR_INTO_S3_FLOW_PRODUCER = "UPLOAD_AVATAR_INTO_S3_FLOW_PRODUCER";
export const UPLOAD_AVATAR_INTO_S3_JOB = "UPLOAD_AVATAR_INTO_S3_JOB";
