export const RESET_BALANCE_QUEUE = "RESET_BALANCE_QUEUE";
export const RESET_BALANCE_QUEUE_FLOW_PRODUCER = "RESET_BALANCE_QUEUE_FLOW_PRODUCER";
export const RESET_BALANCE_QUEUE_JOB = "RESET_BALANCE_QUEUE_JOB";
